### ISSUE TITLE
Support firebase-admin 11.x

### ISSUE THREAD

**Issue by luke-rogers** [proficientai/firewalk#47]
Currently, this library only supports firebase-admin `9.x` and `10.x`. We should add support for `11.x`.

There have been some typing changes in `11.x` so this is a bit more involved than just updating the dependencies to `11.x` as there are some compilation issues, mainly around the introduction of making `firestore.UpdateData` generic.

**Comment by kafkas** [comment]
This is done in #48 and #49. Merged and released v2.
